name: Run CI Tests
on: [push]
jobs:
  run-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          skip-cache: true
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Run Go Vet
        run: |
          make vet
      - name: Run Go Test
        run: |
          make test

