name: Run CI Tests
on: [push]
env:
  GO_VERSION: 1.18.6
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Run Go Vet
        run: |
          go vet ./...
      - name: Run Go Test
        run: |
          go test -race -v ./...
